const data = {
    rooms: [
        {
            roomNumber: "201",
            capacity: 2,
            roomType: "Standard",
            availability: true,
            pricePerDay: 3000,
        },
        {
            roomNumber: "202",
            capacity: 1,
            roomType: "Deluxe",
            availability: false,
            pricePerDay: 5000,
        },
        {
            roomNumber: "203",
            capacity: 2,
            roomType: "Executive",
            availability: false,
            pricePerDay: 7000,
        },
        {
            roomNumber: "204",
            capacity: 1,
            roomType: "Presidential",
            availability: true,
            pricePerDay: 7000,
        },
        {
            roomNumber: "205",
            capacity: 3,
            roomType: "Standard",
            availability: true,
            pricePerDay: 4500,
        },
        {
            roomNumber: "206",
            capacity: 2,
            roomType: "Executive",
            availability: false,
            pricePerDay: 7000,
        },
        {
            roomNumber: "301",
            capacity: 2,
            roomType: "Standard",
            availability: true,
            pricePerDay: 3000,
        },
        {
            roomNumber: "302",
            capacity: 1,
            roomType: "Deluxe",
            availability: false,
            pricePerDay: 5000,
        },
        {
            roomNumber: "303",
            capacity: 2,
            roomType: "Executive",
            availability: false,
            pricePerDay: 7000,
        },
        {
            roomNumber: "304",
            capacity: 1,
            roomType: "Presidential",
            availability: true,
            pricePerDay: 7000,
        },
        {
            roomNumber: "305",
            capacity: 3,
            roomType: "Standard",
            availability: true,
            pricePerDay: 4500,
        },
        {
            roomNumber: "401",
            capacity: 2,
            roomType: "Standard",
            availability: true,
            pricePerDay: 3000,
        },
        {
            roomNumber: "402",
            capacity: 1,
            roomType: "Deluxe",
            availability: false,
            pricePerDay: 5000,
        },
        {
            roomNumber: "403",
            capacity: 2,
            roomType: "Executive",
            availability: false,
            pricePerDay: 7000,
        },
        {
            roomNumber: "404",
            capacity: 1,
            roomType: "Presidential",
            availability: true,
            pricePerDay: 7000,
        },
        {
            roomNumber: "405",
            capacity: 3,
            roomType: "Standard",
            availability: true,
            pricePerDay: 4500,
        },
        {
            roomNumber: "501",
            capacity: 2,
            roomType: "Standard",
            availability: true,
            pricePerDay: 3000,
        },
        {
            roomNumber: "502",
            capacity: 1,
            roomType: "Deluxe",
            availability: false,
            pricePerDay: 5000,
        },
        {
            roomNumber: "503",
            capacity: 2,
            roomType: "Executive",
            availability: false,
            pricePerDay: 7000,
        },
        {
            roomNumber: "504",
            capacity: 1,
            roomType: "Presidential",
            availability: true,
            pricePerDay: 7000,
        },
        {
            roomNumber: "505",
            capacity: 3,
            roomType: "Standard",
            availability: true,
            pricePerDay: 4500,
        },
    ],
    staffs:[
        {
            name: "Rahadul Islam",
            gender: "male",
            dob: "01/08/1996",
            phone: "0171718965",
            email: "rahadul.islam@gmail.com",
            address: "Narayanganj, Bangladesh",
            department: "Management",
            employmentStatus: "full time",
            dateOfJoining: "10/03/2009",
            salary: "250000",
            type: "Manager",
            code: "0"
        },
    ]
};