const data = {
    rooms: [
        {
            roomNumber: "201",
            capacity: 2,
            roomType: "Standard",
            availability: true,
            pricePerDay: 3000,
        },
        {
            roomNumber: "202",
            capacity: 1,
            roomType: "Deluxe",
            availability: false,
            pricePerDay: 5000,
        },
        {
            roomNumber: "203",
            capacity: 2,
            roomType: "Executive",
            availability: false,
            pricePerDay: 7000,
        },
        {
            roomNumber: "204",
            capacity: 1,
            roomType: "Presidential",
            availability: true,
            pricePerDay: 7000,
        },
        {
            roomNumber: "205",
            capacity: 3,
            roomType: "Standard",
            availability: true,
            pricePerDay: 4500,
        },
        {
            roomNumber: "206",
            capacity: 2,
            roomType: "Executive",
            availability: false,
            pricePerDay: 7000,
        },
        {
            roomNumber: "301",
            capacity: 2,
            roomType: "Standard",
            availability: true,
            pricePerDay: 3000,
        },
        {
            roomNumber: "302",
            capacity: 1,
            roomType: "Deluxe",
            availability: false,
            pricePerDay: 5000,
        },
        {
            roomNumber: "303",
            capacity: 2,
            roomType: "Executive",
            availability: false,
            pricePerDay: 7000,
        },
        {
            roomNumber: "304",
            capacity: 1,
            roomType: "Presidential",
            availability: true,
            pricePerDay: 7000,
        },
        {
            roomNumber: "305",
            capacity: 3,
            roomType: "Standard",
            availability: true,
            pricePerDay: 4500,
        },
        {
            roomNumber: "401",
            capacity: 2,
            roomType: "Standard",
            availability: true,
            pricePerDay: 3000,
        },
        {
            roomNumber: "402",
            capacity: 1,
            roomType: "Deluxe",
            availability: false,
            pricePerDay: 5000,
        },
        {
            roomNumber: "403",
            capacity: 2,
            roomType: "Executive",
            availability: false,
            pricePerDay: 7000,
        },
        {
            roomNumber: "404",
            capacity: 1,
            roomType: "Presidential",
            availability: true,
            pricePerDay: 7000,
        },
        {
            roomNumber: "405",
            capacity: 3,
            roomType: "Standard",
            availability: true,
            pricePerDay: 4500,
        },
        {
            roomNumber: "501",
            capacity: 2,
            roomType: "Standard",
            availability: true,
            pricePerDay: 3000,
        },
        {
            roomNumber: "502",
            capacity: 1,
            roomType: "Deluxe",
            availability: false,
            pricePerDay: 5000,
        },
        {
            roomNumber: "503",
            capacity: 2,
            roomType: "Executive",
            availability: false,
            pricePerDay: 7000,
        },
        {
            roomNumber: "504",
            capacity: 1,
            roomType: "Presidential",
            availability: true,
            pricePerDay: 7000,
        },
        {
            roomNumber: "505",
            capacity: 3,
            roomType: "Standard",
            availability: true,
            pricePerDay: 4500,
        },
    ],
    staffs:[
        {
            name: "Rahadul Islam",
            gender: "male",
            dob: "01/08/1996",
            phone: "0171718965",
            email: "rahadul.islam@gmail.com",
            address: "Narayanganj, Bangladesh",
            department: "Management",
            employmentStatus: "full time",
            dateOfJoining: "10/03/2009",
            salary: "250000",
            type: "Manager",
            code: "0"
        },
        {
            name: "Sultan Ahmed",
            gender: "Male",
            dob: "19/07/2000",
            phone: "01451432587",
            email: "sultan.ahmed@gmail.com",
            address: "Mirpur, Dhaka",
            department: "Front desk",
            employmentStatus: "Part-time",
            dateOfJoining: "12/01/2019",
            salary: "20000",
            type: "frontDeskStaff",
            code: "1"
        },
        {
            name: "Halima Akter",
            gender: "Female",
            dob: "19/07/1993",
            phone: "01458569587",
            email: "halima.akter@gmail.com",
            address: "Uttara, Dhaka",
            department: "Front desk",
            employmentStatus: "Full-time",
            dateOfJoining: "19/08/2012",
            salary: "25000",
            type: "frontDeskStaff",
            code: "1"
        },
        
        {
            name: "Abdul Khaleque",
            gender: "Male",
            dob: "26/03/1990",
            phone: "01362547785",
            email: "abdul.khaleque@gmail.com",
            address: "Banani, Dhaka",
            department: "Front desk",
            employmentStatus: "Full-time",
            dateOfJoining: "03/06/2010",
            salary: "26000",
            type: "frontDeskStaff",
            code: "1"
        },
         {
            name: "Anika Ferdous",
            gender: "Female",
            dob: "15/09/2002",
            phone: "01362253998",
            email: "anika.ferdous@gmail.com",
            address: "Kakrail, Dhaka",
            department: "Front desk",
            employmentStatus: "Part-time",
            dateOfJoining: "01/08/2022",
            salary: "18000",
            type: "frontDeskStaff",
            code: "1"
        },
    ],
    
};
